### ISSUE TITLE
Is there a plan to publish Fluent Python 2nd?

### ISSUE THREAD

**Issue by xianfuxing** [fluentpython/example-code#30]
For Python 3.6 and Python 3.7

**Comment by ramalho** [comment]
I have started work on a 2nd edition. My goal is to finish by 2020, but I am not writing full-time, so that may change. Thanks for your interest!

**Comment by ramalho** [comment]
Question answered. Thanks for asking!

**Comment by pdlinh307** [comment]
I am still waiting for the second edition to buy it.
