### ISSUE TITLE
Illegal copy of book found.

### ISSUE THREAD

**Issue by Destaq** [fluentpython/example-code#39]
Hello sir,

@ramalho I found a GitHub repository with your book downloadable as a .pdf there. I don't know if you allowed that to be put up there, but if not then there's the link: https://github.com/EvanLi/programming-book-3/tree/master/Python

This repository also has dozens of other O'Reilly books for download, not sure if that was intentional but would like to notify you nonetheless. Other than that, I have the paperback book and it is super useful, thank you!

**Comment by ramalho** [comment]
Thanks for reporting it.
